// =====================Login=================
export const RESET_MESSAGE = 'RESET_MESSAGE';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_PROGRESS = "LOGIN_PROGRESS";

export const LOGOUT_PROGRESS = "LOGOUT_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// =====================Employee=================

export const GET_EMPLOYEE_LIST_PROGRESS = "GET_EMPLOYEE_LIST_PROGRESS";
export const GET_EMPLOYEE_LIST_SUCCESS = "GET_EMPLOYEE_LIST_SUCCESS";
export const GET_EMPLOYEE_LIST_FAILURE = "GET_EMPLOYEE_LIST_FAILURE";

export const ADD_EMPLOYEE_PROGRESS = "ADD_EMPLOYEE_PROGRESS";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_FAILURE = "ADD_EMPLOYEE_FAILURE";

export const EDIT_DELETE_EMPLOYEE_PROGRESS = "EDIT_DELETE_EMPLOYEE_PROGRESS";
export const EDIT_DELETE_EMPLOYEE_SUCCESS = "EDIT_DELETE_EMPLOYEE_SUCCESS";
export const EDIT_DELETE_EMPLOYEE_FAILURE = "EDIT_DELETE_EMPLOYEE_FAILURE";

// =====================visitor_purpose=================


export const GET_VISITOR_PURPOSE_LIST_PROGRESS = "GET_VISITOR_PURPOSE_LIST_PROGRESS";
export const GET_VISITOR_PURPOSE_LIST_SUCCESS = "GET_VISITOR_PURPOSE_LIST_SUCCESS";
export const GET_VISITOR_PURPOSE_LIST_FAILURE = "GET_VISITOR_PURPOSE_LIST_FAILURE";

export const ADD_VISITOR_PURPOSE_PROGRESS = "ADD_VISITOR_PURPOSE_PROGRESS";
export const ADD_VISITOR_PURPOSE_SUCCESS = "ADD_VISITOR_PURPOSE_SUCCESS";
export const ADD_VISITOR_PURPOSE_FAILURE = "ADD_VISITOR_PURPOSE_FAILURE";

export const EDIT_DELETE_VISITOR_PURPOSE_PROGRESS = "EDIT_DELETE_VISITOR_PURPOSE_PROGRESS";
export const EDIT_DELETE_VISITOR_PURPOSE_SUCCESS = "EDIT_DELETE_VISITOR_PURPOSE_SUCCESS";
export const EDIT_DELETE_VISITOR_PURPOSE_FAILURE = "EDIT_DELETE_VISITOR_PURPOSE_FAILURE";

// =====================Department=================


export const GET_DEPARTMENT_LIST_PROGRESS = "GET_DEPARTMENT_LIST_PROGRESS";
export const GET_DEPARTMENT_LIST_SUCCESS = "GET_DEPARTMENT_LIST_SUCCESS";
export const GET_DEPARTMENT_LIST_FAILURE = "GET_DEPARTMENT_LIST_FAILURE";

export const ADD_DEPARTMENT_PROGRESS = "ADD_DEPARTMENT_PROGRESS";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const EDIT_DELETE_DEPARTMENT_PROGRESS = "EDIT_DELETE_DEPARTMENT_PROGRESS";
export const EDIT_DELETE_DEPARTMENT_SUCCESS = "EDIT_DELETE_DEPARTMENT_SUCCESS";
export const EDIT_DELETE_DEPARTMENT_FAILURE = "EDIT_DELETE_DEPARTMENT_FAILURE";

// =====================COMPANY=================

export const GET_COMPANY_LIST_PROGRESS = "GET_COMPANY_LIST_PROGRESS";
export const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS";
export const GET_COMPANY_LIST_FAILURE = "GET_COMPANY_LIST_FAILURE";

export const ADD_COMPANY_PROGRESS = "ADD_COMPANY_PROGRESS";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAILURE = "ADD_COMPANY_FAILURE";

export const EDIT_DELETE_COMPANY_PROGRESS = "EDIT_DELETE_COMPANY_PROGRESS";
export const EDIT_DELETE_COMPANY_SUCCESS = "EDIT_DELETE_COMPANY_SUCCESS";
export const EDIT_DELETE_COMPANY_FAILURE = "EDIT_DELETE_COMPANY_FAILURE";


// =====================INVITATION OR VISITOR=================


export const GET_INVITATION_OR_VISITOR_LIST_PROGRESS = "GET_INVITATION_OR_VISITOR_LIST_PROGRESS";
export const GET_INVITATION_OR_VISITOR_LIST_SUCCESS = "GET_INVITATION_OR_VISITOR_LIST_SUCCESS";
export const GET_INVITATION_OR_VISITOR_LIST_FAILURE = "GET_INVITATION_OR_VISITOR_LIST_FAILURE";


export const ADD_INVITATION_OR_VISITOR_PROGRESS = "ADD_INVITATION_OR_VISITOR_PROGRESS";
export const ADD_INVITATION_OR_VISITOR_SUCCESS = "ADD_INVITATION_OR_VISITOR_SUCCESS";
export const ADD_INVITATION_OR_VISITOR_FAILURE = "ADD_INVITATION_OR_VISITOR_FAILURE";

export const EDIT_DELETE_INVITATION_OR_VISITOR_PROGRESS = "EDIT_DELETE_INVITATION_OR_VISITOR_PROGRESS";
export const EDIT_DELETE_INVITATION_OR_VISITOR_SUCCESS = "EDIT_DELETE_INVITATION_OR_VISITOR_SUCCESS";
export const EDIT_DELETE_INVITATION_OR_VISITOR_FAILURE = "EDIT_DELETE_INVITATION_OR_VISITOR_FAILURE";

export const UPLOAD_ID_PROOF_VISITORS_PROGRESS = "UPLOAD_ID_PROOF_VISITORS_PROGRESS";
export const UPLOAD_ID_PROOF_VISITORS_SUCCESS = "UPLOAD_ID_PROOF_VISITORS_SUCCESS";
export const UPLOAD_ID_PROOF_VISITORS_FAILURE = "UPLOAD_ID_PROOF_VISITORS_FAILURE";

export const UPLOAD_PHOTO_VISITORS_PROGRESS = "UPLOAD_PHOTO_VISITORS_PROGRESS";
export const UPLOAD_PHOTO_VISITORS_SUCCESS = "UPLOAD_PHOTO_VISITORS_SUCCESS";
export const UPLOAD_PHOTO_VISITORS_FAILURE = "UPLOAD_PHOTO_VISITORS_FAILURE";

// ===================== DATE COUNT INVITATION OR VISITOR=================

export const GET_DATEWISE_VISITORS_PROGRESS = "GET_DATEWISE_VISITORS_PROGRESS";
export const GET_DATEWISE_VISITORS_SUCCESS = "GET_DATEWISE_VISITORS_SUCCESS";
export const GET_DATEWISE_VISITORS_FAILURE = "GET_DATEWISE_VISITORS_FAILURE";

// ===================== DATE COUNT INVITATION OR VISITOR TOMMOROW=========

export const GET_TOMMOROWDATES_VISITORS_PROGRESS = "GET_TOMMOROWDATES_VISITORS_PROGRESS";
export const GET_TOMMOROWDATES_VISITORS_SUCCESS = "GET_TOMMOROWDATES_VISITORS_SUCCESS";
export const GET_TOMMOROWDATES_VISITORS_FAILURE = "GET_TOMMOROWDATES_VISITORS_FAILURE";

// ===================== DATE COUNT INVITATION OR VISITOR NEXT 7 DAYS=========

export const GET_NEXTDATES_VISITORS_PROGRESS = "GET_NEXTDATES_VISITORS_PROGRESS";
export const GET_NEXTDATES_VISITORS_SUCCESS = "GET_NEXTDATES_VISITORS_SUCCESS";
export const GET_NEXTDATES_VISITORS_FAILURE = "GET_NEXTDATES_VISITORS_FAILURE";

// ===================== DATE COUNT EXPIRED INVITATION OR VISITOR NEXT 7 DAYS====

export const GET_EXPIRED_VISITORS_PROGRESS = "GET_EXPIRED_VISITORS_PROGRESS";
export const GET_EXPIRED_VISITORS_SUCCESS = "GET_EXPIRED_VISITORS_SUCCESS";
export const GET_EXPIRED_VISITORS_FAILURE = "GET_EXPIRED_VISITORS_FAILURE";

// ===================== ALL INVITED STATUS VISITORS ============

export const GET_ALLINVITES_VISITORS_PROGRESS = "GET_ALLINVITES_VISITORS_PROGRESS";
export const GET_ALLINVITES_VISITORS_SUCCESS = "GET_ALLINVITES_VISITORS_SUCCESS";
export const GET_ALLINVITES_VISITORS_FAILURE = "GET_ALLINVITES_VISITORS_FAILURE";

// ===================== ALL IN INVITED VISITORS ============ 

export const GET_INTODAYS_VISITORS_PROGRESS = "GET_INTODAYS_VISITORS_PROGRESS";
export const GET_INTODAYS_VISITORS_SUCCESS = "GET_INTODAYS_VISITORS_SUCCESS";
export const GET_INTODAYS_VISITORS_FAILURE = "GET_INTODAYS_VISITORS_FAILURE";

// ===================== ALL IN INVITED VISITORS ============ 

export const GET_OUTTODAYS_VISITORS_PROGRESS = "GET_OUTTODAYS_VISITORS_PROGRESS";
export const GET_OUTTODAYS_VISITORS_SUCCESS = "GET_OUTTODAYS_VISITORS_SUCCESS";
export const GET_OUTTODAYS_VISITORS_FAILURE = "GET_OUTTODAYS_VISITORS_FAILURE";

// =====================GET ALL TODAYS INVITATION VISITORS ============ 

export const GET_ALLTODAY_VISITORS_PROGRESS = "GET_ALLTODAY_VISITORS_PROGRESS";
export const GET_ALLTODAY_VISITORS_SUCCESS = "GET_ALLTODAY_VISITORS_SUCCESS";
export const GET_ALLTODAY_VISITORS_FAILURE = "GET_ALLTODAY_VISITORS_FAILURE";

// =====================GET ALL WEEKLY INVITATION VISITORS ============ 

export const GET_WEEKLY_VISITORS_PROGRESS = "GET_WEEKLY_VISITORS_PROGRESS";
export const GET_WEEKLY_VISITORS_SUCCESS = "GET_WEEKLY_VISITORS_SUCCESS";
export const GET_WEEKLY_VISITORS_FAILURE = "GET_WEEKLY_VISITORS_FAILURE";

// =====================GET ALL TODAYS INVITATION VISITORS ============ 

export const GET_TODAYS_VISITORS_PROGRESS = "GET_TODAYS_VISITORS_PROGRESS";
export const GET_TODAYS_VISITORS_SUCCESS = "GET_TODAYS_VISITORS_SUCCESS";
export const GET_TODAYS_VISITORS_FAILURE = "GET_TODAYS_VISITORS_FAILURE";

// =====================GET ALL VISITORS ============ 

export const GET_ALL_VISITORS_PROGRESS = "GET_ALL_VISITORS_PROGRESS";
export const GET_ALL_VISITORS_SUCCESS = "GET_ALL_VISITORS_SUCCESS";
export const GET_ALL_VISITORS_FAILURE = "GET_ALL_VISITORS_FAILURE";

// =====================GET ALL EMPLOYEES ============ 

export const GET_ALL_EMPLOYEE_PROGRESS = "GET_ALL_EMPLOYEE_PROGRESS";
export const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS";
export const GET_ALL_EMPLOYEE_FAILURE = "GET_ALL_EMPLOYEE_FAILURE";

// =====================GET CHECKOUT STATUS============ 

export const GET_CHECKOUT_REGISTER_PROGRESS = "GET_CHECKOUT_REGISTER_PROGRESS";
export const GET_CHECKOUT_REGISTER_SUCCESS = "GET_CHECKOUT_REGISTER_SUCCESS";
export const GET_CHECKOUT_REGISTER_FAILURE = "GET_CHECKOUT_REGISTER_FAILURE";

// =====================AVERAGE HRS EXPRESS VISITORS============ 

export const GET_AVEARGE_HRS_EXPRESS_VISITOR_PROGRESS = "GET_AVEARGE_HRS_EXPRESS_VISITOR_PROGRESS";
export const GET_AVEARGE_HRS_EXPRESS_VISITOR_SUCCESS = "GET_AVEARGE_HRS_EXPRESS_VISITOR_SUCCESS";
export const GET_AVEARGE_HRS_EXPRESS_VISITOR_FAILURE = "GET_AVEARGE_HRS_EXPRESS_VISITOR_FAILURE";

// =====================AVERAGE DAY EXPRESS VISITORS============ 

export const GET_AVERAGE_DAY_EXPRESS_VISITOR_PROGRESS = "GET_AVERAGE_DAY_EXPRESS_VISITOR_PROGRESS";
export const GET_AVERAGE_DAY_EXPRESS_VISITOR_SUCCESS = "GET_AVERAGE_DAY_EXPRESS_VISITOR_SUCCESS";
export const GET_AVERAGE_DAY_EXPRESS_VISITOR_FAILURE = "GET_AVERAGE_DAY_EXPRESS_VISITOR_FAILURE";

// =====================Image Upload=================

export const IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS";
export const IMAGE_UPLOAD_FAILURE = "IMAGE_UPLOAD_FAILURE";
export const IMAGE_UPLOAD_PROGRESS = "IMAGE_UPLOAD_PROGRESS";

// =====================Notifications=================

export const ADD_NOTIFICATION_PROGRESS = "ADD_NOTIFICATION_PROGRESS"
export const ADD_NOTIFICATION_SUCCESS = "ADD_NOTIFICATION_SUCCESS"
export const ADD_NOTIFICATION_FAILURE = "ADD_NOTIFICATION_FAILURE"

export const GET_NOTIFICATION_LIST_PROGRESS = "GET_NOTIFICATION_LIST_PROGRESS";
export const GET_NOTIFICATION_LIST_SUCCESS = "GET_NOTIFICATION_LIST_SUCCESS";
export const GET_NOTIFICATION_LIST_FAILURE = "GET_NOTIFICATION_LIST_SUCCESS";

export const GET_ACCEPTED_NOTIFICATION_LIST_PROGRESS = "GET_ACCEPTED_NOTIFICATION_LIST_PROGRESS";
export const GET_ACCEPTED_NOTIFICATION_LIST_SUCCESS = "GET_ACCEPTED_NOTIFICATION_LIST_SUCCESS";
export const GET_ACCEPTED_NOTIFICATION_LIST_FAILURE = "GET_ACCEPTED_NOTIFICATION_LIST_FAILURE";

export const EDIT_DELETE_NOTIFICATION_PROGRESS = "EDIT_DELETE_NOTIFICATION_PROGRESS";
export const EDIT_DELETE_NOTIFICATION_SUCCESS = "EDIT_DELETE_NOTIFICATION_SUCCESS";
export const EDIT_DELETE_NOTIFICATION_FAILURE = "EDIT_DELETE_NOTIFICATION_FAILURE";

export const EDIT_DELETE_CHECKOUTNOTIFICATION_PROGRESS = "EDIT_DELETE_CHECKOUTNOTIFICATION_PROGRESS";
export const EDIT_DELETE_CHECKOUTNOTIFICATION_SUCCESS = "EDIT_DELETE_CHECKOUTNOTIFICATION_SUCCESS";
export const EDIT_DELETE_CHECKOUTNOTIFICATION_FAILURE = "EDIT_DELETE_CHECKOUTNOTIFICATION_FAILURE";

// =====================COMPANY_DETAILS=================
export const GET_COMPANY_DETAILS_LIST_PROGRESS = "GET_COMPANY_DETAILS_LIST_PROGRESS";
export const GET_COMPANY_DETAILS_LIST_SUCCESS = "GET_COMPANY_DETAILS_LIST_SUCCESS";
export const GET_COMPANY_DETAILS_LIST_FAILURE = "GET_COMPANY_DETAILS_LIST_FAILURE";


export const ADD_COMPANY_DETAILS_PROGRESS = "ADD_COMPANY_DETAILS_PROGRESS";
export const ADD_COMPANY_DETAILS_SUCCESS = "ADD_COMPANY_DETAILS_SUCCESS";
export const ADD_COMPANY_DETAILS_FAILURE = "ADD_COMPANY_DETAILS_FAILURE";

export const EDIT_DELETE_COMPANY_DETAILS_PROGRESS = "EDIT_DELETE_COMPANY_DETAILS_PROGRESS";
export const EDIT_DELETE_COMPANY_DETAILS_SUCCESS = "EDIT_DELETE_COMPANY_DETAILS_SUCCESS";
export const EDIT_DELETE_COMPANY_DETAILS_FAILURE = "EDIT_DELETE_COMPANY_DETAILS_FAILURE";

// =====================SECURITY=================
export const GET_SECURITY_LIST_PROGRESS = "GET_SECURITY_LIST_PROGRESS";
export const GET_SECURITY_LIST_SUCCESS = "GET_SECURITY_LIST_SUCCESS";
export const GET_SECURITY_LIST_FAILURE = "GET_SECURITY_LIST_FAILURE";


export const ADD_SECURITY_PROGRESS = "ADD_SECURITY_PROGRESS";
export const ADD_SECURITY_SUCCESS = "ADD_SECURITY_SUCCESS";
export const ADD_SECURITY_FAILURE = "ADD_SECURITY_FAILURE";

export const EDIT_DELETE_SECURITY_PROGRESS = "EDIT_DELETE_SECURITY_PROGRESS";
export const EDIT_DELETE_SECURITY_SUCCESS = "EDIT_DELETE_SECURITY_SUCCESS";
export const EDIT_DELETE_SECURITY_FAILURE = "EDIT_DELETE_SECURITY_FAILURE";

export const UPLOAD_AADHAR_SECURITY_PROGRESS = "UPLOAD_AADHAR_SECURITY_PROGRESS";
export const UPLOAD_AADHAR_SECURITY_SUCCESS = "UPLOAD_AADHAR_SECURITY_SUCCESS";
export const UPLOAD_AADHAR_SECURITY_FAILURE = "UPLOAD_AADHAR_SECURITY_FAILURE";

export const GENERATE_CODE_PROGRESS = "GENERATE_CODE_PROGRESS";
export const GENERATE_CODE_SUCCESS = "GENERATE_CODE_SUCCESS";
export const GENERATE_CODE_FAILURE = "GENERATE_CODE_FAILURE";

export const GET_VISITOR_DETAILS_THROUGH_CODE_PROGRESS = "GET_VISITOR_DETAILS_THROUGH_CODE_PROGRESS";
export const GET_VISITOR_DETAILS_THROUGH_CODE_SUCCESS = "GET_VISITOR_DETAILS_THROUGH_CODE_SUCCESS";
export const GET_VISITOR_DETAILS_THROUGH_CODE_FAILURE = "GET_VISITOR_DETAILS_THROUGH_CODE_FAILURE";

// =====================COMPANY DETAILS=================
